//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTSUBTYPE
    {
        public ADVERTSUBTYPE()
        {
            this.ADVERT = new HashSet<ADVERT>();
        }
    
        public long ABST_ID { get; set; }
        public string ABST_CODE { get; set; }
        public string ABST_DESCRIPTION { get; set; }
        public Nullable<long> ABST_ADVERTMAINTYPEID { get; set; }
    
        public virtual ICollection<ADVERT> ADVERT { get; set; }
        public virtual ADVERTMAINTYPE ADVERTMAINTYPE { get; set; }
    }
}
