//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERT
    {
        public long ADVT_ID { get; set; }
        public string ADVT_DESCRIPTION { get; set; }
        public Nullable<long> ADVT_USERID { get; set; }
        public Nullable<System.DateTime> ADVT_ADVERTDATETIME { get; set; }
        public Nullable<long> ADVT_ADVERTMAINTYPEID { get; set; }
        public Nullable<long> ADVT_ADVERTSUBTYPEID { get; set; }
        public Nullable<bool> ADVT_ISOPEN { get; set; }
        public byte[] ADVT_IMAGE { get; set; }
        public string ADVT_PHONE { get; set; }
        public string ADVT_MAIL { get; set; }
        public Nullable<int> ADVT_PRICE { get; set; }
    
        public virtual ADVERTMAINTYPE ADVERTMAINTYPE { get; set; }
        public virtual ADVERTSUBTYPE ADVERTSUBTYPE { get; set; }
        public virtual APPUSER APPUSER { get; set; }
    }
}
