//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTMAINTYPE
    {
        public ADVERTMAINTYPE()
        {
            this.ADVERT = new HashSet<ADVERT>();
            this.ADVERTSUBTYPE = new HashSet<ADVERTSUBTYPE>();
        }
    
        public long ADTT_ID { get; set; }
        public string ADTT_CODE { get; set; }
        public string ADTT_DESCRIPTION { get; set; }
    
        public virtual ICollection<ADVERT> ADVERT { get; set; }
        public virtual ICollection<ADVERTSUBTYPE> ADVERTSUBTYPE { get; set; }
    }
}
