//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUSER
    {
        public APPUSER()
        {
            this.ADVERT = new HashSet<ADVERT>();
        }
    
        public long USER_ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_NAMESURNAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PHONE { get; set; }
        public Nullable<System.DateTime> USER_SIGNUPDATE { get; set; }
    
        public virtual ICollection<ADVERT> ADVERT { get; set; }
    }
}
