//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityGraduationProjectEntities : DbContext
    {
        public UniversityGraduationProjectEntities()
            : base("name=UniversityGraduationProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADVERT> ADVERT { get; set; }
        public DbSet<ADVERTMAINTYPE> ADVERTMAINTYPE { get; set; }
        public DbSet<ADVERTSUBTYPE> ADVERTSUBTYPE { get; set; }
        public DbSet<APPUSER> APPUSER { get; set; }
    }
}
