//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTMAINTYPE), "ADVERT", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTSUBTYPE), "ADVERT", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_USER", "APPUSER", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.APPUSER), "ADVERT", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTMAINTYPE), "ADVERTSUBTYPE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERTSUBTYPE))]

// Original file name:
// Generation date: 18.04.2016 21:35:14
namespace WebServices.Entity
{
    
    /// <summary>
    /// There are no comments for GRADUATIONModel.ADVERT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ADVT_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ADVERT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ADVERT object.
        /// </summary>
        /// <param name="aDVT_ID">Initial value of ADVT_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ADVERT CreateADVERT(long aDVT_ID)
        {
            ADVERT aDVERT = new ADVERT();
            aDVERT.ADVT_ID = aDVT_ID;
            return aDVERT;
        }
        /// <summary>
        /// There are no comments for property ADVT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ADVT_ID
        {
            get
            {
                return this._ADVT_ID;
            }
            set
            {
                this.OnADVT_IDChanging(value);
                this.ReportPropertyChanging("ADVT_ID");
                this._ADVT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ADVT_ID");
                this.OnADVT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ADVT_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_IDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_IDChanged();
        /// <summary>
        /// There are no comments for property ADVT_DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ADVT_DESCRIPTION
        {
            get
            {
                return this._ADVT_DESCRIPTION;
            }
            set
            {
                this.OnADVT_DESCRIPTIONChanging(value);
                this.ReportPropertyChanging("ADVT_DESCRIPTION");
                this._ADVT_DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADVT_DESCRIPTION");
                this.OnADVT_DESCRIPTIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ADVT_DESCRIPTION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_DESCRIPTIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_DESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for property ADVT_ADVERTDATETIME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> ADVT_ADVERTDATETIME
        {
            get
            {
                return this._ADVT_ADVERTDATETIME;
            }
            set
            {
                this.OnADVT_ADVERTDATETIMEChanging(value);
                this.ReportPropertyChanging("ADVT_ADVERTDATETIME");
                this._ADVT_ADVERTDATETIME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ADVT_ADVERTDATETIME");
                this.OnADVT_ADVERTDATETIMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _ADVT_ADVERTDATETIME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_ADVERTDATETIMEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_ADVERTDATETIMEChanged();
        /// <summary>
        /// There are no comments for property ADVT_ISOPEN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> ADVT_ISOPEN
        {
            get
            {
                return this._ADVT_ISOPEN;
            }
            set
            {
                this.OnADVT_ISOPENChanging(value);
                this.ReportPropertyChanging("ADVT_ISOPEN");
                this._ADVT_ISOPEN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ADVT_ISOPEN");
                this.OnADVT_ISOPENChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _ADVT_ISOPEN;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_ISOPENChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_ISOPENChanged();
        /// <summary>
        /// There are no comments for property ADVT_IMAGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte[] ADVT_IMAGE
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._ADVT_IMAGE);
            }
            set
            {
                this.OnADVT_IMAGEChanging(value);
                this.ReportPropertyChanging("ADVT_IMAGE");
                this._ADVT_IMAGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADVT_IMAGE");
                this.OnADVT_IMAGEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte[] _ADVT_IMAGE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_IMAGEChanging(byte[] value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_IMAGEChanged();
        /// <summary>
        /// There are no comments for property ADVT_PHONE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ADVT_PHONE
        {
            get
            {
                return this._ADVT_PHONE;
            }
            set
            {
                this.OnADVT_PHONEChanging(value);
                this.ReportPropertyChanging("ADVT_PHONE");
                this._ADVT_PHONE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADVT_PHONE");
                this.OnADVT_PHONEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ADVT_PHONE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_PHONEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_PHONEChanged();
        /// <summary>
        /// There are no comments for property ADVT_MAIL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ADVT_MAIL
        {
            get
            {
                return this._ADVT_MAIL;
            }
            set
            {
                this.OnADVT_MAILChanging(value);
                this.ReportPropertyChanging("ADVT_MAIL");
                this._ADVT_MAIL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADVT_MAIL");
                this.OnADVT_MAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ADVT_MAIL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_MAILChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADVT_MAILChanged();
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ADVERTMAINTYPE ADVERTMAINTYPE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ADVERTMAINTYPE> ADVERTMAINTYPEReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ADVERTSUBTYPE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ADVERTSUBTYPE ADVERTSUBTYPE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ADVERTSUBTYPE in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ADVERTSUBTYPE> ADVERTSUBTYPEReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for APPUSER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_USER", "APPUSER")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public APPUSER APPUSER
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for APPUSER in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<APPUSER> APPUSERReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRADUATIONModel.ADVERTMAINTYPE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ADTT_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERTMAINTYPE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ADVERTMAINTYPE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ADVERTMAINTYPE object.
        /// </summary>
        /// <param name="aDTT_ID">Initial value of ADTT_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ADVERTMAINTYPE CreateADVERTMAINTYPE(long aDTT_ID)
        {
            ADVERTMAINTYPE aDVERTMAINTYPE = new ADVERTMAINTYPE();
            aDVERTMAINTYPE.ADTT_ID = aDTT_ID;
            return aDVERTMAINTYPE;
        }
        /// <summary>
        /// There are no comments for property ADTT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ADTT_ID
        {
            get
            {
                return this._ADTT_ID;
            }
            set
            {
                this.OnADTT_IDChanging(value);
                this.ReportPropertyChanging("ADTT_ID");
                this._ADTT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ADTT_ID");
                this.OnADTT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ADTT_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_IDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_IDChanged();
        /// <summary>
        /// There are no comments for property ADTT_CODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ADTT_CODE
        {
            get
            {
                return this._ADTT_CODE;
            }
            set
            {
                this.OnADTT_CODEChanging(value);
                this.ReportPropertyChanging("ADTT_CODE");
                this._ADTT_CODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADTT_CODE");
                this.OnADTT_CODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ADTT_CODE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_CODEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_CODEChanged();
        /// <summary>
        /// There are no comments for property ADTT_DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ADTT_DESCRIPTION
        {
            get
            {
                return this._ADTT_DESCRIPTION;
            }
            set
            {
                this.OnADTT_DESCRIPTIONChanging(value);
                this.ReportPropertyChanging("ADTT_DESCRIPTION");
                this._ADTT_DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ADTT_DESCRIPTION");
                this.OnADTT_DESCRIPTIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ADTT_DESCRIPTION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_DESCRIPTIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnADTT_DESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for ADVERT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERT")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERT", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ADVERTSUBTYPE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ADVERTSUBTYPE> ADVERTSUBTYPE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ADVERTSUBTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ADVERTSUBTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRADUATIONModel.ADVERTSUBTYPE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ABST_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERTSUBTYPE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ADVERTSUBTYPE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ADVERTSUBTYPE object.
        /// </summary>
        /// <param name="aBST_ID">Initial value of ABST_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ADVERTSUBTYPE CreateADVERTSUBTYPE(long aBST_ID)
        {
            ADVERTSUBTYPE aDVERTSUBTYPE = new ADVERTSUBTYPE();
            aDVERTSUBTYPE.ABST_ID = aBST_ID;
            return aDVERTSUBTYPE;
        }
        /// <summary>
        /// There are no comments for property ABST_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ABST_ID
        {
            get
            {
                return this._ABST_ID;
            }
            set
            {
                this.OnABST_IDChanging(value);
                this.ReportPropertyChanging("ABST_ID");
                this._ABST_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ABST_ID");
                this.OnABST_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ABST_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_IDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_IDChanged();
        /// <summary>
        /// There are no comments for property ABST_CODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ABST_CODE
        {
            get
            {
                return this._ABST_CODE;
            }
            set
            {
                this.OnABST_CODEChanging(value);
                this.ReportPropertyChanging("ABST_CODE");
                this._ABST_CODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ABST_CODE");
                this.OnABST_CODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ABST_CODE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_CODEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_CODEChanged();
        /// <summary>
        /// There are no comments for property ABST_DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ABST_DESCRIPTION
        {
            get
            {
                return this._ABST_DESCRIPTION;
            }
            set
            {
                this.OnABST_DESCRIPTIONChanging(value);
                this.ReportPropertyChanging("ABST_DESCRIPTION");
                this._ABST_DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ABST_DESCRIPTION");
                this.OnABST_DESCRIPTIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ABST_DESCRIPTION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_DESCRIPTIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABST_DESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for ADVERT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERT")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERT", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ADVERTMAINTYPE ADVERTMAINTYPE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ADVERTMAINTYPE> ADVERTMAINTYPEReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRADUATIONModel.APPUSER in the schema.
    /// </summary>
    /// <KeyProperties>
    /// USER_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="APPUSER")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class APPUSER : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new APPUSER object.
        /// </summary>
        /// <param name="uSER_ID">Initial value of USER_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static APPUSER CreateAPPUSER(long uSER_ID)
        {
            APPUSER aPPUSER = new APPUSER();
            aPPUSER.USER_ID = uSER_ID;
            return aPPUSER;
        }
        /// <summary>
        /// There are no comments for property USER_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long USER_ID
        {
            get
            {
                return this._USER_ID;
            }
            set
            {
                this.OnUSER_IDChanging(value);
                this.ReportPropertyChanging("USER_ID");
                this._USER_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("USER_ID");
                this.OnUSER_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _USER_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_IDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_IDChanged();
        /// <summary>
        /// There are no comments for property USER_CODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string USER_CODE
        {
            get
            {
                return this._USER_CODE;
            }
            set
            {
                this.OnUSER_CODEChanging(value);
                this.ReportPropertyChanging("USER_CODE");
                this._USER_CODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("USER_CODE");
                this.OnUSER_CODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _USER_CODE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_CODEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_CODEChanged();
        /// <summary>
        /// There are no comments for property USER_PASSWORD in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string USER_PASSWORD
        {
            get
            {
                return this._USER_PASSWORD;
            }
            set
            {
                this.OnUSER_PASSWORDChanging(value);
                this.ReportPropertyChanging("USER_PASSWORD");
                this._USER_PASSWORD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("USER_PASSWORD");
                this.OnUSER_PASSWORDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _USER_PASSWORD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_PASSWORDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_PASSWORDChanged();
        /// <summary>
        /// There are no comments for property USER_NAMESURNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string USER_NAMESURNAME
        {
            get
            {
                return this._USER_NAMESURNAME;
            }
            set
            {
                this.OnUSER_NAMESURNAMEChanging(value);
                this.ReportPropertyChanging("USER_NAMESURNAME");
                this._USER_NAMESURNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("USER_NAMESURNAME");
                this.OnUSER_NAMESURNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _USER_NAMESURNAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_NAMESURNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_NAMESURNAMEChanged();
        /// <summary>
        /// There are no comments for property USER_EMAIL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string USER_EMAIL
        {
            get
            {
                return this._USER_EMAIL;
            }
            set
            {
                this.OnUSER_EMAILChanging(value);
                this.ReportPropertyChanging("USER_EMAIL");
                this._USER_EMAIL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("USER_EMAIL");
                this.OnUSER_EMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _USER_EMAIL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_EMAILChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_EMAILChanged();
        /// <summary>
        /// There are no comments for property USER_PHONE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string USER_PHONE
        {
            get
            {
                return this._USER_PHONE;
            }
            set
            {
                this.OnUSER_PHONEChanging(value);
                this.ReportPropertyChanging("USER_PHONE");
                this._USER_PHONE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("USER_PHONE");
                this.OnUSER_PHONEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _USER_PHONE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_PHONEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_PHONEChanged();
        /// <summary>
        /// There are no comments for property USER_SIGNUPDATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> USER_SIGNUPDATE
        {
            get
            {
                return this._USER_SIGNUPDATE;
            }
            set
            {
                this.OnUSER_SIGNUPDATEChanging(value);
                this.ReportPropertyChanging("USER_SIGNUPDATE");
                this._USER_SIGNUPDATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("USER_SIGNUPDATE");
                this.OnUSER_SIGNUPDATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _USER_SIGNUPDATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_SIGNUPDATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUSER_SIGNUPDATEChanged();
        /// <summary>
        /// There are no comments for ADVERT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_USER", "ADVERT")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_USER", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_USER", "ADVERT", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRADUATIONEntities in the schema.
    /// </summary>
    public partial class GRADUATIONEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GRADUATIONEntities object using the connection string found in the 'GRADUATIONEntities' section of the application configuration file.
        /// </summary>
        public GRADUATIONEntities() : 
                base("name=GRADUATIONEntities", "GRADUATIONEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GRADUATIONEntities object.
        /// </summary>
        public GRADUATIONEntities(string connectionString) : 
                base(connectionString, "GRADUATIONEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GRADUATIONEntities object.
        /// </summary>
        public GRADUATIONEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GRADUATIONEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ADVERT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ADVERT> ADVERT
        {
            get
            {
                if ((this._ADVERT == null))
                {
                    this._ADVERT = base.CreateQuery<ADVERT>("[ADVERT]");
                }
                return this._ADVERT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ADVERT> _ADVERT;
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ADVERTMAINTYPE> ADVERTMAINTYPE
        {
            get
            {
                if ((this._ADVERTMAINTYPE == null))
                {
                    this._ADVERTMAINTYPE = base.CreateQuery<ADVERTMAINTYPE>("[ADVERTMAINTYPE]");
                }
                return this._ADVERTMAINTYPE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ADVERTMAINTYPE> _ADVERTMAINTYPE;
        /// <summary>
        /// There are no comments for ADVERTSUBTYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ADVERTSUBTYPE> ADVERTSUBTYPE
        {
            get
            {
                if ((this._ADVERTSUBTYPE == null))
                {
                    this._ADVERTSUBTYPE = base.CreateQuery<ADVERTSUBTYPE>("[ADVERTSUBTYPE]");
                }
                return this._ADVERTSUBTYPE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ADVERTSUBTYPE> _ADVERTSUBTYPE;
        /// <summary>
        /// There are no comments for APPUSER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<APPUSER> APPUSER
        {
            get
            {
                if ((this._APPUSER == null))
                {
                    this._APPUSER = base.CreateQuery<APPUSER>("[APPUSER]");
                }
                return this._APPUSER;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<APPUSER> _APPUSER;
        /// <summary>
        /// There are no comments for ADVERT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToADVERT(ADVERT aDVERT)
        {
            base.AddObject("ADVERT", aDVERT);
        }
        /// <summary>
        /// There are no comments for ADVERTMAINTYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToADVERTMAINTYPE(ADVERTMAINTYPE aDVERTMAINTYPE)
        {
            base.AddObject("ADVERTMAINTYPE", aDVERTMAINTYPE);
        }
        /// <summary>
        /// There are no comments for ADVERTSUBTYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToADVERTSUBTYPE(ADVERTSUBTYPE aDVERTSUBTYPE)
        {
            base.AddObject("ADVERTSUBTYPE", aDVERTSUBTYPE);
        }
        /// <summary>
        /// There are no comments for APPUSER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToAPPUSER(APPUSER aPPUSER)
        {
            base.AddObject("APPUSER", aPPUSER);
        }
    }
}
