//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTMAINTYPE), "ADVERT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTSUBTYPE), "ADVERT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: EdmRelationshipAttribute("GRADUATIONModel", "FK_ADVT_USER", "APPUSER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.APPUSER), "ADVERT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERT))]
[assembly: EdmRelationshipAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebServices.Entity.ADVERTMAINTYPE), "ADVERTSUBTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebServices.Entity.ADVERTSUBTYPE))]

#endregion

namespace WebServices.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GRADUATIONEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GRADUATIONEntities object using the connection string found in the 'GRADUATIONEntities' section of the application configuration file.
        /// </summary>
        public GRADUATIONEntities() : base("name=GRADUATIONEntities", "GRADUATIONEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GRADUATIONEntities object.
        /// </summary>
        public GRADUATIONEntities(string connectionString) : base(connectionString, "GRADUATIONEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GRADUATIONEntities object.
        /// </summary>
        public GRADUATIONEntities(EntityConnection connection) : base(connection, "GRADUATIONEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ADVERT> ADVERT
        {
            get
            {
                if ((_ADVERT == null))
                {
                    _ADVERT = base.CreateObjectSet<ADVERT>("ADVERT");
                }
                return _ADVERT;
            }
        }
        private ObjectSet<ADVERT> _ADVERT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ADVERTMAINTYPE> ADVERTMAINTYPE
        {
            get
            {
                if ((_ADVERTMAINTYPE == null))
                {
                    _ADVERTMAINTYPE = base.CreateObjectSet<ADVERTMAINTYPE>("ADVERTMAINTYPE");
                }
                return _ADVERTMAINTYPE;
            }
        }
        private ObjectSet<ADVERTMAINTYPE> _ADVERTMAINTYPE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ADVERTSUBTYPE> ADVERTSUBTYPE
        {
            get
            {
                if ((_ADVERTSUBTYPE == null))
                {
                    _ADVERTSUBTYPE = base.CreateObjectSet<ADVERTSUBTYPE>("ADVERTSUBTYPE");
                }
                return _ADVERTSUBTYPE;
            }
        }
        private ObjectSet<ADVERTSUBTYPE> _ADVERTSUBTYPE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<APPUSER> APPUSER
        {
            get
            {
                if ((_APPUSER == null))
                {
                    _APPUSER = base.CreateObjectSet<APPUSER>("APPUSER");
                }
                return _APPUSER;
            }
        }
        private ObjectSet<APPUSER> _APPUSER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ADVERT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToADVERT(ADVERT aDVERT)
        {
            base.AddObject("ADVERT", aDVERT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ADVERTMAINTYPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToADVERTMAINTYPE(ADVERTMAINTYPE aDVERTMAINTYPE)
        {
            base.AddObject("ADVERTMAINTYPE", aDVERTMAINTYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ADVERTSUBTYPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToADVERTSUBTYPE(ADVERTSUBTYPE aDVERTSUBTYPE)
        {
            base.AddObject("ADVERTSUBTYPE", aDVERTSUBTYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the APPUSER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAPPUSER(APPUSER aPPUSER)
        {
            base.AddObject("APPUSER", aPPUSER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADVERT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ADVERT object.
        /// </summary>
        /// <param name="aDVT_ID">Initial value of the ADVT_ID property.</param>
        public static ADVERT CreateADVERT(global::System.Int64 aDVT_ID)
        {
            ADVERT aDVERT = new ADVERT();
            aDVERT.ADVT_ID = aDVT_ID;
            return aDVERT;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ADVT_ID
        {
            get
            {
                return _ADVT_ID;
            }
            set
            {
                if (_ADVT_ID != value)
                {
                    OnADVT_IDChanging(value);
                    ReportPropertyChanging("ADVT_ID");
                    _ADVT_ID = StructuralObject.SetValidValue(value, "ADVT_ID");
                    ReportPropertyChanged("ADVT_ID");
                    OnADVT_IDChanged();
                }
            }
        }
        private global::System.Int64 _ADVT_ID;
        partial void OnADVT_IDChanging(global::System.Int64 value);
        partial void OnADVT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADVT_DESCRIPTION
        {
            get
            {
                return _ADVT_DESCRIPTION;
            }
            set
            {
                OnADVT_DESCRIPTIONChanging(value);
                ReportPropertyChanging("ADVT_DESCRIPTION");
                _ADVT_DESCRIPTION = StructuralObject.SetValidValue(value, true, "ADVT_DESCRIPTION");
                ReportPropertyChanged("ADVT_DESCRIPTION");
                OnADVT_DESCRIPTIONChanged();
            }
        }
        private global::System.String _ADVT_DESCRIPTION;
        partial void OnADVT_DESCRIPTIONChanging(global::System.String value);
        partial void OnADVT_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ADVT_ADVERTDATETIME
        {
            get
            {
                return _ADVT_ADVERTDATETIME;
            }
            set
            {
                OnADVT_ADVERTDATETIMEChanging(value);
                ReportPropertyChanging("ADVT_ADVERTDATETIME");
                _ADVT_ADVERTDATETIME = StructuralObject.SetValidValue(value, "ADVT_ADVERTDATETIME");
                ReportPropertyChanged("ADVT_ADVERTDATETIME");
                OnADVT_ADVERTDATETIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ADVT_ADVERTDATETIME;
        partial void OnADVT_ADVERTDATETIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnADVT_ADVERTDATETIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ADVT_ISOPEN
        {
            get
            {
                return _ADVT_ISOPEN;
            }
            set
            {
                OnADVT_ISOPENChanging(value);
                ReportPropertyChanging("ADVT_ISOPEN");
                _ADVT_ISOPEN = StructuralObject.SetValidValue(value, "ADVT_ISOPEN");
                ReportPropertyChanged("ADVT_ISOPEN");
                OnADVT_ISOPENChanged();
            }
        }
        private Nullable<global::System.Boolean> _ADVT_ISOPEN;
        partial void OnADVT_ISOPENChanging(Nullable<global::System.Boolean> value);
        partial void OnADVT_ISOPENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ADVT_IMAGE
        {
            get
            {
                return StructuralObject.GetValidValue(_ADVT_IMAGE);
            }
            set
            {
                OnADVT_IMAGEChanging(value);
                ReportPropertyChanging("ADVT_IMAGE");
                _ADVT_IMAGE = StructuralObject.SetValidValue(value, true, "ADVT_IMAGE");
                ReportPropertyChanged("ADVT_IMAGE");
                OnADVT_IMAGEChanged();
            }
        }
        private global::System.Byte[] _ADVT_IMAGE;
        partial void OnADVT_IMAGEChanging(global::System.Byte[] value);
        partial void OnADVT_IMAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADVT_PHONE
        {
            get
            {
                return _ADVT_PHONE;
            }
            set
            {
                OnADVT_PHONEChanging(value);
                ReportPropertyChanging("ADVT_PHONE");
                _ADVT_PHONE = StructuralObject.SetValidValue(value, true, "ADVT_PHONE");
                ReportPropertyChanged("ADVT_PHONE");
                OnADVT_PHONEChanged();
            }
        }
        private global::System.String _ADVT_PHONE;
        partial void OnADVT_PHONEChanging(global::System.String value);
        partial void OnADVT_PHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADVT_MAIL
        {
            get
            {
                return _ADVT_MAIL;
            }
            set
            {
                OnADVT_MAILChanging(value);
                ReportPropertyChanging("ADVT_MAIL");
                _ADVT_MAIL = StructuralObject.SetValidValue(value, true, "ADVT_MAIL");
                ReportPropertyChanged("ADVT_MAIL");
                OnADVT_MAILChanged();
            }
        }
        private global::System.String _ADVT_MAIL;
        partial void OnADVT_MAILChanging(global::System.String value);
        partial void OnADVT_MAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ADVT_PRICE
        {
            get
            {
                return _ADVT_PRICE;
            }
            set
            {
                OnADVT_PRICEChanging(value);
                ReportPropertyChanging("ADVT_PRICE");
                _ADVT_PRICE = StructuralObject.SetValidValue(value, "ADVT_PRICE");
                ReportPropertyChanged("ADVT_PRICE");
                OnADVT_PRICEChanged();
            }
        }
        private Nullable<global::System.Int32> _ADVT_PRICE;
        partial void OnADVT_PRICEChanging(Nullable<global::System.Int32> value);
        partial void OnADVT_PRICEChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE")]
        public ADVERTMAINTYPE ADVERTMAINTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ADVERTMAINTYPE> ADVERTMAINTYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERTMAINTYPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE")]
        public ADVERTSUBTYPE ADVERTSUBTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ADVERTSUBTYPE> ADVERTSUBTYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ADVERTSUBTYPE>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERTSUBTYPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_USER", "APPUSER")]
        public APPUSER APPUSER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<APPUSER> APPUSERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<APPUSER>("GRADUATIONModel.FK_ADVT_USER", "APPUSER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERTMAINTYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADVERTMAINTYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ADVERTMAINTYPE object.
        /// </summary>
        /// <param name="aDTT_ID">Initial value of the ADTT_ID property.</param>
        public static ADVERTMAINTYPE CreateADVERTMAINTYPE(global::System.Int64 aDTT_ID)
        {
            ADVERTMAINTYPE aDVERTMAINTYPE = new ADVERTMAINTYPE();
            aDVERTMAINTYPE.ADTT_ID = aDTT_ID;
            return aDVERTMAINTYPE;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ADTT_ID
        {
            get
            {
                return _ADTT_ID;
            }
            set
            {
                if (_ADTT_ID != value)
                {
                    OnADTT_IDChanging(value);
                    ReportPropertyChanging("ADTT_ID");
                    _ADTT_ID = StructuralObject.SetValidValue(value, "ADTT_ID");
                    ReportPropertyChanged("ADTT_ID");
                    OnADTT_IDChanged();
                }
            }
        }
        private global::System.Int64 _ADTT_ID;
        partial void OnADTT_IDChanging(global::System.Int64 value);
        partial void OnADTT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADTT_CODE
        {
            get
            {
                return _ADTT_CODE;
            }
            set
            {
                OnADTT_CODEChanging(value);
                ReportPropertyChanging("ADTT_CODE");
                _ADTT_CODE = StructuralObject.SetValidValue(value, true, "ADTT_CODE");
                ReportPropertyChanged("ADTT_CODE");
                OnADTT_CODEChanged();
            }
        }
        private global::System.String _ADTT_CODE;
        partial void OnADTT_CODEChanging(global::System.String value);
        partial void OnADTT_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADTT_DESCRIPTION
        {
            get
            {
                return _ADTT_DESCRIPTION;
            }
            set
            {
                OnADTT_DESCRIPTIONChanging(value);
                ReportPropertyChanging("ADTT_DESCRIPTION");
                _ADTT_DESCRIPTION = StructuralObject.SetValidValue(value, true, "ADTT_DESCRIPTION");
                ReportPropertyChanged("ADTT_DESCRIPTION");
                OnADTT_DESCRIPTIONChanged();
            }
        }
        private global::System.String _ADTT_DESCRIPTION;
        partial void OnADTT_DESCRIPTIONChanging(global::System.String value);
        partial void OnADTT_DESCRIPTIONChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTMAINTYPE", "ADVERT")]
        public EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTMAINTYPE", "ADVERT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE")]
        public EntityCollection<ADVERTSUBTYPE> ADVERTSUBTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADVERTSUBTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADVERTSUBTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTSUBTYPE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="ADVERTSUBTYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADVERTSUBTYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ADVERTSUBTYPE object.
        /// </summary>
        /// <param name="aBST_ID">Initial value of the ABST_ID property.</param>
        public static ADVERTSUBTYPE CreateADVERTSUBTYPE(global::System.Int64 aBST_ID)
        {
            ADVERTSUBTYPE aDVERTSUBTYPE = new ADVERTSUBTYPE();
            aDVERTSUBTYPE.ABST_ID = aBST_ID;
            return aDVERTSUBTYPE;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ABST_ID
        {
            get
            {
                return _ABST_ID;
            }
            set
            {
                if (_ABST_ID != value)
                {
                    OnABST_IDChanging(value);
                    ReportPropertyChanging("ABST_ID");
                    _ABST_ID = StructuralObject.SetValidValue(value, "ABST_ID");
                    ReportPropertyChanged("ABST_ID");
                    OnABST_IDChanged();
                }
            }
        }
        private global::System.Int64 _ABST_ID;
        partial void OnABST_IDChanging(global::System.Int64 value);
        partial void OnABST_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ABST_CODE
        {
            get
            {
                return _ABST_CODE;
            }
            set
            {
                OnABST_CODEChanging(value);
                ReportPropertyChanging("ABST_CODE");
                _ABST_CODE = StructuralObject.SetValidValue(value, true, "ABST_CODE");
                ReportPropertyChanged("ABST_CODE");
                OnABST_CODEChanged();
            }
        }
        private global::System.String _ABST_CODE;
        partial void OnABST_CODEChanging(global::System.String value);
        partial void OnABST_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ABST_DESCRIPTION
        {
            get
            {
                return _ABST_DESCRIPTION;
            }
            set
            {
                OnABST_DESCRIPTIONChanging(value);
                ReportPropertyChanging("ABST_DESCRIPTION");
                _ABST_DESCRIPTION = StructuralObject.SetValidValue(value, true, "ABST_DESCRIPTION");
                ReportPropertyChanged("ABST_DESCRIPTION");
                OnABST_DESCRIPTIONChanged();
            }
        }
        private global::System.String _ABST_DESCRIPTION;
        partial void OnABST_DESCRIPTIONChanging(global::System.String value);
        partial void OnABST_DESCRIPTIONChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_ADVERTSUBTYPE", "ADVERT")]
        public EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_ADVERTSUBTYPE", "ADVERT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE")]
        public ADVERTMAINTYPE ADVERTMAINTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ADVERTMAINTYPE> ADVERTMAINTYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ADVERTMAINTYPE>("GRADUATIONModel.FK_ABST_ADVERTMAINTYPE", "ADVERTMAINTYPE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRADUATIONModel", Name="APPUSER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class APPUSER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new APPUSER object.
        /// </summary>
        /// <param name="uSER_ID">Initial value of the USER_ID property.</param>
        public static APPUSER CreateAPPUSER(global::System.Int64 uSER_ID)
        {
            APPUSER aPPUSER = new APPUSER();
            aPPUSER.USER_ID = uSER_ID;
            return aPPUSER;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                if (_USER_ID != value)
                {
                    OnUSER_IDChanging(value);
                    ReportPropertyChanging("USER_ID");
                    _USER_ID = StructuralObject.SetValidValue(value, "USER_ID");
                    ReportPropertyChanged("USER_ID");
                    OnUSER_IDChanged();
                }
            }
        }
        private global::System.Int64 _USER_ID;
        partial void OnUSER_IDChanging(global::System.Int64 value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_CODE
        {
            get
            {
                return _USER_CODE;
            }
            set
            {
                OnUSER_CODEChanging(value);
                ReportPropertyChanging("USER_CODE");
                _USER_CODE = StructuralObject.SetValidValue(value, true, "USER_CODE");
                ReportPropertyChanged("USER_CODE");
                OnUSER_CODEChanged();
            }
        }
        private global::System.String _USER_CODE;
        partial void OnUSER_CODEChanging(global::System.String value);
        partial void OnUSER_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_PASSWORD
        {
            get
            {
                return _USER_PASSWORD;
            }
            set
            {
                OnUSER_PASSWORDChanging(value);
                ReportPropertyChanging("USER_PASSWORD");
                _USER_PASSWORD = StructuralObject.SetValidValue(value, true, "USER_PASSWORD");
                ReportPropertyChanged("USER_PASSWORD");
                OnUSER_PASSWORDChanged();
            }
        }
        private global::System.String _USER_PASSWORD;
        partial void OnUSER_PASSWORDChanging(global::System.String value);
        partial void OnUSER_PASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_NAMESURNAME
        {
            get
            {
                return _USER_NAMESURNAME;
            }
            set
            {
                OnUSER_NAMESURNAMEChanging(value);
                ReportPropertyChanging("USER_NAMESURNAME");
                _USER_NAMESURNAME = StructuralObject.SetValidValue(value, true, "USER_NAMESURNAME");
                ReportPropertyChanged("USER_NAMESURNAME");
                OnUSER_NAMESURNAMEChanged();
            }
        }
        private global::System.String _USER_NAMESURNAME;
        partial void OnUSER_NAMESURNAMEChanging(global::System.String value);
        partial void OnUSER_NAMESURNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_EMAIL
        {
            get
            {
                return _USER_EMAIL;
            }
            set
            {
                OnUSER_EMAILChanging(value);
                ReportPropertyChanging("USER_EMAIL");
                _USER_EMAIL = StructuralObject.SetValidValue(value, true, "USER_EMAIL");
                ReportPropertyChanged("USER_EMAIL");
                OnUSER_EMAILChanged();
            }
        }
        private global::System.String _USER_EMAIL;
        partial void OnUSER_EMAILChanging(global::System.String value);
        partial void OnUSER_EMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_PHONE
        {
            get
            {
                return _USER_PHONE;
            }
            set
            {
                OnUSER_PHONEChanging(value);
                ReportPropertyChanging("USER_PHONE");
                _USER_PHONE = StructuralObject.SetValidValue(value, true, "USER_PHONE");
                ReportPropertyChanged("USER_PHONE");
                OnUSER_PHONEChanged();
            }
        }
        private global::System.String _USER_PHONE;
        partial void OnUSER_PHONEChanging(global::System.String value);
        partial void OnUSER_PHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> USER_SIGNUPDATE
        {
            get
            {
                return _USER_SIGNUPDATE;
            }
            set
            {
                OnUSER_SIGNUPDATEChanging(value);
                ReportPropertyChanging("USER_SIGNUPDATE");
                _USER_SIGNUPDATE = StructuralObject.SetValidValue(value, "USER_SIGNUPDATE");
                ReportPropertyChanged("USER_SIGNUPDATE");
                OnUSER_SIGNUPDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _USER_SIGNUPDATE;
        partial void OnUSER_SIGNUPDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnUSER_SIGNUPDATEChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRADUATIONModel", "FK_ADVT_USER", "ADVERT")]
        public EntityCollection<ADVERT> ADVERT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_USER", "ADVERT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADVERT>("GRADUATIONModel.FK_ADVT_USER", "ADVERT", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
